### ISSUE TITLE
Trabajos relacionados

### ISSUE THREAD

**Issue by dma1004** [dma1004/TFG-SemiSupervisado#1]

**Comment by alvarag** [comment]
Algún otro comentario:

[anexosAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10811785/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10811788/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Y otros pocos ;)

[memoriaAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10859571/memoriaAAG.pdf)

[anexosAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10859569/anexosAAG.pdf)

**Comment by alvarag** [comment]
Comentarios, igual esta issue ya se puede cerrar, no? ;)

[memoriaAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10981801/memoriaAAG.pdf)


[anexosAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10981798/anexosAAG.pdf)

**Comment by dma1004** [comment]
Mejor, una cosa menos :)
