### ISSUE TITLE
Añadir conceptos teóricos aprendizaje

### ISSUE THREAD

**Issue by dma1004** [dma1004/TFG-SemiSupervisado#2]

**Comment by alvarag** [comment]
Comentarios sobre la memoria. 

[memoriaAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10075387/memoriaAAG.pdf)


Recuerda ir escribiendo en anexos la parte relativa a cada uno de los sprint, que luego se olvida.

**Comment by dma1004** [comment]
Me pongo con las correcciones (menos yoda),  muchas gracias.

**Comment by alvarag** [comment]
Algunos comentarios sobre memoria y anexos

[memoriaAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10544334/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/10544341/anexosAAG.pdf)
