### ISSUE TITLE
Arreglar bug carga de datasets

### ISSUE THREAD

**Issue by dmacha27** [dma1004/TFG-SemiSupervisado#38]
Para algunos conjuntos de datos que contienen -1 como etiquetas, el proceso de carga falla

**Comment by alvarag** [comment]
Un par de comentarios en la pantalla de carga de datasets:
- Deja seleccionar cualquier archivo pero luego si no es csv o arff falla con una excepción bastante fea. Mejor que solo deje seleccionar/cargar ficheros con extensión esperada.
- El botón "Test file" siempre está activo y te descarga un un arff concreto.

**Comment by dma1004** [comment]
Okey, al dar a configuración se retorna a la pestaña de subida con mensaje de error. El botón "Test file" se ha renombrado a "Download test file"
