### ISSUE TITLE
Diagramas de despliegue y de componentes

### ISSUE THREAD

**Issue by dma1004** [dma1004/TFG-SemiSupervisado#64]
Anexo C: Diseño

**Comment by alvarag** [comment]
Comentarios en la memoria, importante: ¡líneas futuras!

[memoriaAAG.pdf](https://github.com/dma1004/TFG-SemiSupervisado/files/11651844/memoriaAAG.pdf)

**Comment by dma1004** [comment]
@alvarag Actualizada! (con líneas futuras)
